# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\"4\n\x11\x45valuationRequest\x12\x0e\n\x06sample\x18\x01 \x01(\t\x12\x0f\n\x07ndarray\x18\x02 \x01(\x0c\"\x8e\x01\n\x12\x45valuationResponse\x12.\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x1c.EvaluationResponse.Decision\x12\x0f\n\x07ndarray\x18\x02 \x01(\x0c\x12\x12\n\nexperience\x18\x03 \x01(\x05\"#\n\x08\x44\x65\x63ision\x12\n\n\x06\x42\x45NiGN\x10\x00\x12\x0b\n\x07\x41NOMALY\x10\x01\"\x1a\n\x0cStateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\rStateResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x12\n\nexperience\x18\x02 \x01(\x05\x32p\n\x05\x41gent\x12:\n\rGetEvaluation\x12\x12.EvaluationRequest\x1a\x13.EvaluationResponse\"\x00\x12+\n\x08GetState\x12\r.StateRequest\x1a\x0e.StateResponse\"\x00\x62\x06proto3')



_EVALUATIONREQUEST = DESCRIPTOR.message_types_by_name['EvaluationRequest']
_EVALUATIONRESPONSE = DESCRIPTOR.message_types_by_name['EvaluationResponse']
_STATEREQUEST = DESCRIPTOR.message_types_by_name['StateRequest']
_STATERESPONSE = DESCRIPTOR.message_types_by_name['StateResponse']
_EVALUATIONRESPONSE_DECISION = _EVALUATIONRESPONSE.enum_types_by_name['Decision']
EvaluationRequest = _reflection.GeneratedProtocolMessageType('EvaluationRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationRequest)
  })
_sym_db.RegisterMessage(EvaluationRequest)

EvaluationResponse = _reflection.GeneratedProtocolMessageType('EvaluationResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONRESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:EvaluationResponse)
  })
_sym_db.RegisterMessage(EvaluationResponse)

StateRequest = _reflection.GeneratedProtocolMessageType('StateRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATEREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:StateRequest)
  })
_sym_db.RegisterMessage(StateRequest)

StateResponse = _reflection.GeneratedProtocolMessageType('StateResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATERESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:StateResponse)
  })
_sym_db.RegisterMessage(StateResponse)

_AGENT = DESCRIPTOR.services_by_name['Agent']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVALUATIONREQUEST._serialized_start=15
  _EVALUATIONREQUEST._serialized_end=67
  _EVALUATIONRESPONSE._serialized_start=70
  _EVALUATIONRESPONSE._serialized_end=212
  _EVALUATIONRESPONSE_DECISION._serialized_start=177
  _EVALUATIONRESPONSE_DECISION._serialized_end=212
  _STATEREQUEST._serialized_start=214
  _STATEREQUEST._serialized_end=240
  _STATERESPONSE._serialized_start=242
  _STATERESPONSE._serialized_end=292
  _AGENT._serialized_start=294
  _AGENT._serialized_end=406
# @@protoc_insertion_point(module_scope)
