# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class AgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvaluation = channel.unary_unary(
            "/Agent/GetEvaluation",
            request_serializer=agent__pb2.EvaluationRequest.SerializeToString,
            response_deserializer=agent__pb2.EvaluationResponse.FromString,
        )
        self.GetState = channel.unary_unary(
            "/Agent/GetState",
            request_serializer=agent__pb2.StateRequest.SerializeToString,
            response_deserializer=agent__pb2.StateResponse.FromString,
        )


class AgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvaluation(self, request, context):
        """Agent handles evaluation requests from other agents.."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetEvaluation": grpc.unary_unary_rpc_method_handler(
            servicer.GetEvaluation,
            request_deserializer=agent__pb2.EvaluationRequest.FromString,
            response_serializer=agent__pb2.EvaluationResponse.SerializeToString,
        ),
        "GetState": grpc.unary_unary_rpc_method_handler(
            servicer.GetState,
            request_deserializer=agent__pb2.StateRequest.FromString,
            response_serializer=agent__pb2.StateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("Agent", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Agent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvaluation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Agent/GetEvaluation",
            agent__pb2.EvaluationRequest.SerializeToString,
            agent__pb2.EvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Agent/GetState",
            agent__pb2.StateRequest.SerializeToString,
            agent__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
